'''
Once we've identified a daughter artery (a final branch), we need 4 things:

- Ostium: Where the artery leaves the aorta
- Seed: A point 5 mm outward from the ostium along the vessel
- Radius: Local vessel radius at the seed
- Direction: Unit vector pointing from the ostium into the branch

ostium = fimd_ostium(...)
seed = find_seed(...)
direction = calculate_direction(...)
radius = estimate_radius(...)

'''
import numpy as np
from scipy.ndimage import distance_transform_edt # type: ignore
import SimpleITK as sitk

def extract_ostium(candidate):
    """
    Extracts the ostium coordinates from a detected candidate.
    
    Parameters
    ----------
    candidate : dict
        A candidate dictionary generated by detection.py and passed 
        through filtering.py.
        
    Returns
    -------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    ostium_index_xyz : list of int
        The [x, y, z] voxel index of the ostium within the cropped image.
    """
    ostium_xyz_mm = candidate["point_xyz_mm"]
    ostium_index_xyz = candidate["index_xyz"]
    
    return ostium_xyz_mm, ostium_index_xyz

def find_seed(ostium_xyz_mm, centerline_points_mm):
    """
    Finds the seed point 5 mm outward from the ostium along the vessel.
    
    Parameters
    ----------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    centerline_points_mm : list of list of float
        An ordered list of physical [x, y, z] coordinates representing the 
        vessel's centerline, starting from the ostium and moving outward.
        
    Returns
    -------
    seed_xyz_mm : list of float
        The physical [x, y, z] coordinates of the seed point.
    """
    ostium = np.array(ostium_xyz_mm)
    
    for point in centerline_points_mm:
        current_point = np.array(point)
        
        # Calculate the Euclidean distance in physical millimeters
        distance_mm = np.linalg.norm(current_point - ostium)
        
        # Stop as soon as we cross the 5 mm threshold
        if distance_mm >= 5.0:
            return current_point.tolist()
            
    # Fallback: if the branch terminates before 5 mm, return the furthest traced point
    if centerline_points_mm:
        return centerline_points_mm[-1]
    
    return ostium_xyz_mm

def calculate_direction(ostium_xyz_mm, seed_xyz_mm):
    """
    Calculates the unit direction vector from the ostium to the seed point.
    
    Parameters
    ----------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    seed_xyz_mm : list of float
        The physical [x, y, z] coordinates of the seed point in millimeters.
        
    Returns
    -------
    direction_vector : list of float
        A unit vector pointing from the ostium to the seed point.
    """
    ostium = np.array(ostium_xyz_mm, dtype=float)
    seed = np.array(seed_xyz_mm, dtype=float)

    vector = seed - ostium
    magnitude = np.linalg.norm(vector)

    if magnitude == 0.0:
        return [0.0,0.0,0.0]
    unit_vector = vector / magnitude
    return unit_vector.tolist()

def estimate_radius(seed_xyz_mm, component_mask, spacing):
    """
    Estimates the vessel radius at the seed point in physical millimeters.
    
    Parameters
    ----------
    seed_index_xyz : list or tuple of int
        The [x, y, z] voxel index of the seed point.
    component_mask : numpy.ndarray
        A 3D binary mask of the isolated branch component in NumPy (z, y, x) order.
    spacing : tuple or list of float
        Voxel spacing in SimpleITK (x, y, z) order[cite: 2].
        
    Returns
    -------
    radius_mm : float
        The local vessel radius at the seed point in mm.
    """

    # SimpleITK spacing is (x, y, z), but NumPy shape/indexing is (z, y, x)[cite: 2].
    # We reverse the spacing to match the (z, y, x) sampling order for the distance transform.
    spacing_zyx = tuple(reversed(spacing))  

    # Calculate distance map where every voxel value is its physical distance to the background (mm)
    distance_map = distance_transform_edt(component_mask, sampling=spacing_zyx)

    x, y, z = seed_xyz_mm

    z = min(max(0,z), component_mask.shape[0]-1)
    y = min(max(0,y), component_mask.shape[1]-1)
    x = min(max(0,x), component_mask.shape[2]-1)       

    radius_mm = float(distance_map[z, y, x])  # Accessing the distance map in (z, y, x) order
    return radius_mm

if __name__ == "__main__":
    print("Testing geometry calculations...")
    
    # 1. Mock a small 3D binary component mask (z, y, x)
    mock_mask = np.zeros((20, 20, 20), dtype=bool)
    mock_mask[5:15, 5:15, 5:15] = True
    
    # 2. Mock inputs
    mock_candidate = {
        "point_xyz_mm": [10.0, 10.0, 10.0],
        "index_xyz": [5, 5, 5]
    }
    mock_spacing = (1.0, 1.0, 1.0) # (x, y, z)
    mock_centerline = [
        [10.0, 10.0, 10.0],
        [12.0, 10.0, 10.0],
        [15.0, 10.0, 10.0] # This passes the 5mm threshold from [10,10,10]
    ]
    
    # 3. Test each function sequentially
    ostium_mm, ostium_idx = extract_ostium(mock_candidate)
    print(f"Ostium (mm): {ostium_mm}, Index: {ostium_idx}")
    
    seed_mm = find_seed(ostium_mm, mock_centerline)
    print(f"Seed (mm): {seed_mm}")
    
    direction = calculate_direction(ostium_mm, seed_mm)
    print(f"Direction Vector: {direction}")
    
    radius = estimate_radius(ostium_idx, mock_mask, mock_spacing)
    print(f"Estimated Radius: {radius} mm")
    
    print("Geometry tests completed successfully!")