'''
Once we've identified a daughter artery (a final branch), we need 4 things:

- Ostium: Where the artery leaves the aorta
- Seed: A point 5 mm outward from the ostium along the vessel
- Radius: Local vessel radius at the seed
- Direction: Unit vector pointing from the ostium into the branch

ostium = fimd_ostium(...)
seed = find_seed(...)
direction = calculate_direction(...)
radius = estimate_radius(...)

'''
import numpy as np
from scipy.ndimage import distance_transform_edt, map_coordinates
import SimpleITK as sitk

def extract_ostium(candidate):
    """
    Extracts the ostium coordinates from a detected candidate.
    
    Parameters
    ----------
    candidate : dict
        A candidate dictionary generated by detection.py and passed 
        through filtering.py.
        
    Returns
    -------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    ostium_index_xyz : list of int
        The [x, y, z] voxel index of the ostium within the cropped image.
    """
    ostium_xyz_mm = candidate["point_xyz_mm"]
    ostium_index_xyz = candidate["index_xyz"]
    
    return ostium_xyz_mm, ostium_index_xyz

def find_seed(ostium_xyz_mm, centerline_points_mm, distance_mm=5.0):
    """
    Finds the seed point 5 mm outward from the ostium along the vessel.
    
    Parameters
    ----------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    centerline_points_mm : list of list of float
        An ordered list of physical [x, y, z] coordinates representing the 
        vessel's centerline, starting from the ostium and moving outward.
        
    Returns
    -------
    seed_xyz_mm : list of float
        The physical [x, y, z] coordinates of the seed point.
    """
    if not np.isfinite(distance_mm) or distance_mm < 0:
        raise ValueError("distance_mm must be finite and non-negative.")
    previous = np.asarray(ostium_xyz_mm, dtype=float)
    remaining = distance_mm
    for point in centerline_points_mm:
        current = np.asarray(point, dtype=float)
        segment_length = float(np.linalg.norm(current - previous))
        if segment_length > 0 and segment_length >= remaining - 1e-9:
            return (previous + min(remaining / segment_length, 1.0) * (current - previous)).tolist()
        remaining -= segment_length
        previous = current
    raise ValueError(f"Centerline does not extend {distance_mm:g} mm from the ostium.")

def calculate_direction(ostium_xyz_mm, seed_xyz_mm):
    """
    Calculates the unit direction vector from the ostium to the seed point.
    
    Parameters
    ----------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    seed_xyz_mm : list of float
        The physical [x, y, z] coordinates of the seed point in millimeters.
        
    Returns
    -------
    direction_vector : list of float
        A unit vector pointing from the ostium to the seed point.
    """
    ostium = np.array(ostium_xyz_mm, dtype=float)
    seed = np.array(seed_xyz_mm, dtype=float)

    vector = seed - ostium
    magnitude = np.linalg.norm(vector)

    if magnitude == 0.0:
        return [0.0,0.0,0.0]
    unit_vector = vector / magnitude
    return unit_vector.tolist()

def estimate_radius(seed_index_xyz, component_mask, spacing):
    """
    Estimates the vessel radius at the seed point in physical millimeters.
    
    Parameters
    ----------
    seed_index_xyz : list or tuple of int
        The [x, y, z] voxel index of the seed point.
    component_mask : numpy.ndarray
        A 3D binary mask of the isolated branch component in NumPy (z, y, x) order.
    spacing : tuple or list of float
        Voxel spacing in SimpleITK (x, y, z) order[cite: 2].
        
    Returns
    -------
    radius_mm : float
        The local vessel radius at the seed point in mm.
    """

    # SimpleITK spacing is (x, y, z), but NumPy shape/indexing is (z, y, x)[cite: 2].
    # We reverse the spacing to match the (z, y, x) sampling order for the distance transform.
    spacing_zyx = tuple(reversed(spacing))
    seed_zyx = np.asarray(seed_index_xyz, dtype=float)[::-1]
    if (seed_zyx.shape != (3,) or not np.isfinite(seed_zyx).all()
            or np.any(seed_zyx < 0) or np.any(seed_zyx > np.asarray(component_mask.shape) - 1)):
        raise ValueError("Seed index must lie inside the component image.")
    # Padding provides background at image borders; interpolation supports a 5 mm seed
    # between voxel centers. This is a voxel-based radius approximation.
    distance_map = distance_transform_edt(np.pad(component_mask.astype(bool), 1),
                                          sampling=spacing_zyx)[1:-1, 1:-1, 1:-1]
    return float(map_coordinates(distance_map, seed_zyx[:, None], order=1)[0])

if __name__ == "__main__":
    print("Testing geometry calculations...")
    
    # 1. Mock a small 3D binary component mask (z, y, x)
    mock_mask = np.zeros((20, 20, 20), dtype=bool)
    mock_mask[5:15, 5:15, 5:15] = True
    
    # 2. Mock inputs
    mock_candidate = {
        "point_xyz_mm": [10.0, 10.0, 10.0],
        "index_xyz": [5, 5, 5]
    }
    mock_spacing = (1.0, 1.0, 1.0) # (x, y, z)
    mock_centerline = [
        [10.0, 10.0, 10.0],
        [12.0, 10.0, 10.0],
        [15.0, 10.0, 10.0] # This passes the 5mm threshold from [10,10,10]
    ]
    
    # 3. Test each function sequentially
    ostium_mm, ostium_idx = extract_ostium(mock_candidate)
    print(f"Ostium (mm): {ostium_mm}, Index: {ostium_idx}")
    
    seed_mm = find_seed(ostium_mm, mock_centerline)
    print(f"Seed (mm): {seed_mm}")
    
    direction = calculate_direction(ostium_mm, seed_mm)
    print(f"Direction Vector: {direction}")
    
    radius = estimate_radius(ostium_idx, mock_mask, mock_spacing)
    print(f"Estimated Radius: {radius} mm")
    
    print("Geometry tests completed successfully!")
