'''
Once we've identified a daughter artery (a final branch), we need 4 things:

- Ostium: Where the artery leaves the aorta
- Seed: A point 5 mm outward from the ostium along the vessel
- Radius: Local vessel radius at the seed
- Direction: Unit vector pointing from the ostium into the branch

ostium = fimd_ostium(...)
seed = find_seed(...)
direction = calculate_direction(...)
radius = estimate_radius(...)

'''
import os
import numpy as np
from scipy.ndimage import distance_transform_edt, map_coordinates
import SimpleITK as sitk

def extract_ostium(candidate):
    """
    Extracts the ostium coordinates from a detected candidate.
    
    Parameters
    ----------
    candidate : dict
        A candidate dictionary generated by detection.py and passed 
        through filtering.py.
        
    Returns
    -------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    ostium_index_xyz : list of int
        The [x, y, z] voxel index of the ostium within the cropped image.
    """
    ostium_xyz_mm = candidate["point_xyz_mm"]
    ostium_index_xyz = candidate["index_xyz"]
    
    return ostium_xyz_mm, ostium_index_xyz

def find_seed(ostium_xyz_mm, centerline_points_mm, distance_mm=5.0):
    """
    Finds the seed point 5 mm outward from the ostium along the vessel.
    
    Parameters
    ----------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    centerline_points_mm : list of list of float
        An ordered list of physical [x, y, z] coordinates representing the 
        vessel's centerline, starting from the ostium and moving outward.
        
    Returns
    -------
    seed_xyz_mm : list of float
        The physical [x, y, z] coordinates of the seed point.
    """
    if not np.isfinite(distance_mm) or distance_mm < 0:
        raise ValueError("distance_mm must be finite and non-negative.")
    previous = np.asarray(ostium_xyz_mm, dtype=float)
    remaining = distance_mm
    for point in centerline_points_mm:
        current = np.asarray(point, dtype=float)
        segment_length = float(np.linalg.norm(current - previous))
        if segment_length > 0 and segment_length >= remaining - 1e-9:
            return (previous + min(remaining / segment_length, 1.0) * (current - previous)).tolist()
        remaining -= segment_length
        previous = current
    raise ValueError(f"Centerline does not extend {distance_mm:g} mm from the ostium.")

def calculate_direction(ostium_xyz_mm, seed_xyz_mm):
    """
    Calculates the unit direction vector from the ostium to the seed point.
    
    Parameters
    ----------
    ostium_xyz_mm : list of float
        The physical [x, y, z] coordinates of the ostium in millimeters.
    seed_xyz_mm : list of float
        The physical [x, y, z] coordinates of the seed point in millimeters.
        
    Returns
    -------
    direction_vector : list of float
        A unit vector pointing from the ostium to the seed point.
    """
    ostium = np.array(ostium_xyz_mm, dtype=float)
    seed = np.array(seed_xyz_mm, dtype=float)

    vector = seed - ostium
    magnitude = np.linalg.norm(vector)

    if magnitude == 0.0:
        return [0.0,0.0,0.0]
    unit_vector = vector / magnitude
    return unit_vector.tolist()

def estimate_radius(seed_index_xyz, component_mask, spacing):
    """
    Estimates the vessel radius at the seed point in physical millimeters.
    
    Parameters
    ----------
    seed_index_xyz : list or tuple of int
        The [x, y, z] voxel index of the seed point.
    component_mask : numpy.ndarray
        A 3D binary mask of the isolated branch component in NumPy (z, y, x) order.
    spacing : tuple or list of float
        Voxel spacing in SimpleITK (x, y, z) order[cite: 2].
        
    Returns
    -------
    radius_mm : float
        The local vessel radius at the seed point in mm.
    """

    # SimpleITK spacing is (x, y, z), but NumPy shape/indexing is (z, y, x)[cite: 2].
    # We reverse the spacing to match the (z, y, x) sampling order for the distance transform.
    spacing_zyx = tuple(reversed(spacing))
    seed_zyx = np.asarray(seed_index_xyz, dtype=float)[::-1]
    if (seed_zyx.shape != (3,) or not np.isfinite(seed_zyx).all()
            or np.any(seed_zyx < 0) or np.any(seed_zyx > np.asarray(component_mask.shape) - 1)):
        raise ValueError("Seed index must lie inside the component image.")
    # Padding provides background at image borders; interpolation supports a 5 mm seed
    # between voxel centers. This is a voxel-based radius approximation.
    distance_map = distance_transform_edt(np.pad(component_mask.astype(bool), 1),
                                          sampling=spacing_zyx)[1:-1, 1:-1, 1:-1]
    return float(map_coordinates(distance_map, seed_zyx[:, None], order=1)[0])


if __name__ == "__main__":
    print("Running integration test with actual .nii files...")
    
    # Locate your dataset files dynamically
    search_dir = os.getcwd()
    found_ct = None
    found_mask = None
    
    for root, dirs, files in os.walk(search_dir):
        for file in files:
            if file == "orig1.nii":
                found_ct = os.path.join(root, file)
            elif file == "mask1.nii":
                found_mask = os.path.join(root, file)
                
    if found_ct and found_mask:
        print(f"Found real dataset! Loading directly...")
        
        # Load directly via SimpleITK to avoid any wrapper issues
        ct_image = sitk.ReadImage(found_ct)
        mask_image = sitk.ReadImage(found_mask)
        spacing = ct_image.GetSpacing()
        
        # Run detection to find real candidates
        from detection import detect_candidates
        candidates = detect_candidates(ct_image, mask_image)
        print(f"Detected {len(candidates)} candidate branch(es).")
        
        if len(candidates) > 0:
            test_candidate = candidates[0]
            print("\nTesting geometry on candidate 0:")
            
            # Extract ostium
            ostium_mm, ostium_idx = extract_ostium(test_candidate)
            print(f"  - Ostium (mm): {ostium_mm}")
            print(f"  - Ostium (index): {ostium_idx}")
            
            # Dummy centerline for find_seed test
            dummy_centerline = [
                ostium_mm,
                [ostium_mm[0] + 2.0, ostium_mm[1], ostium_mm[2]],
                [ostium_mm[0] + 5.5, ostium_mm[1], ostium_mm[2]]
            ]
            seed_mm = find_seed(ostium_mm, dummy_centerline)
            print(f"  - Seed (mm): {seed_mm}")
            
            # Calculate direction
            direction = calculate_direction(ostium_mm, seed_mm)
            print(f"  - Direction Vector: {direction}")
            
            # Estimate radius using mask array
            mask_array = sitk.GetArrayFromImage(mask_image) > 0
            radius = estimate_radius(ostium_idx, mask_array, spacing)
            print(f"  - Estimated Radius: {radius:.2f} mm")
            
        else:
            print("No candidates found to test geometry on.")
    else:
        print("Could not find orig1.nii or mask1.nii in the directory.")